apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: {{ .Values.nodepool.name }}
  namespace: {{ .Values.namespace }}
  labels:
    strimzi.io/cluster: {{ .Values.kafka.clusterName }}
spec:
  roles: {{ toYaml .Values.nodepool.roles | nindent 4 }}
  replicas: {{ .Values.nodepool.replicas }}
  storage:
    type: {{ .Values.nodepool.storage.type }}
    size: {{ .Values.nodepool.storage.size }}
