apiVersion: v2
name: strimzi-kafka-helm-chart
description: Advanced Helm chart for deploying Kafka (KRaft) cluster using Strimzi Operator with multiple deployment modes
type: application
version: 0.3.0
appVersion: "0.48.0"
home: https://github.com/Zaissler/strimzi-kafka-helm-chart
sources:
  - https://github.com/Zaissler/strimzi-kafka-helm-chart
keywords:
  - kafka
  - strimzi
  - kraft
  - kubernetes
  - helm
maintainers:
  - name: Zaissler
    email: zaissler@gmail.com
